# load required libraries
library(rcdk)

# ==============================================================================
# calculate all positive adducts
# ==============================================================================
## create list with all the adduct definitoins
adduct_list_pos <- list(
  
  # triple charged -----------------------------------------------------------
  "[M+3H]3+"      = list(mass_multi = 1 / 3,
                         mass_add = (3 * get.formula("H", charge = 1)@mass) / 3,
                         formula_add = "H3",
                         formula_sub = NA_character_,
                         charge = 3),
  "[M+2H+Na]3+"   = list(mass_multi = 1 / 3,
                         mass_add = (2 * get.formula("H", charge = 1)@mass + 1 * get.formula("Na", charge = 1)@mass) / 3,
                         formula_add = "H2Na",
                         formula_sub = NA_character_,
                         charge = 3),
  "[M+H+Na2]3+"   = list(mass_multi = 1 / 3,
                         mass_add = (1 * get.formula("H", charge = 1)@mass + 2 * get.formula("Na", charge = 1)@mass) / 3,
                         formula_add = "HNa2",
                         formula_sub = NA_character_,
                         charge = 3),
  "[M+Na3]3+"     = list(mass_multi = 1 / 3,
                         mass_add = (3 * get.formula("Na", charge = 1)@mass) / 3,
                         formula_add = "Na3",
                         formula_sub = NA_character_,
                         charge = 3),
  
  # double charged -----------------------------------------------------------
  "[M+2H]2+"      = list(mass_multi = 1 / 2,
                         mass_add = (2 * get.formula("H", charge = 1)@mass) / 2,
                         formula_add = "H2",
                         formula_sub = NA_character_,
                         charge = 2),
  "[M+H+NH4]2+"   = list(mass_multi = 1 / 2,
                         mass_add = (get.formula("H", charge = 1)@mass + get.formula("NH4", charge = 1)@mass) / 2,
                         formula_add = "NH5",
                         formula_sub = NA_character_,
                         charge = 2),
  "[M+H+K]2+"     = list(mass_multi = 1 / 2,
                         mass_add = (get.formula("H", charge = 1)@mass + get.formula("K", charge = 1)@mass) / 2,
                         formula_add = "HK",
                         formula_sub = NA_character_,
                         charge = 2),
  "[M+H+Na]2+"    = list(mass_multi = 1 / 2,
                         mass_add = (get.formula("H", charge = 1)@mass + get.formula("Na", charge = 1)@mass) / 2,
                         formula_add = "HNa",
                         formula_sub = NA_character_,
                         charge = 2),
  "[M+C2H3N+2H]2+"= list(mass_multi = 1 / 2,
                         mass_add = (2 * get.formula("H", charge = 1)@mass + get.formula("C2H3N", charge = 0)@mass) / 2,
                         formula_add = "C2H5N",
                         formula_sub = NA_character_,
                         charge = 2),
  "[M+2Na]2+"     = list(mass_multi = 1 / 2,
                         mass_add = 2 * get.formula("Na", charge = 1)@mass / 2,
                         formula_add = "Na2",
                         formula_sub = NA_character_,
                         charge = 2),
  "[M+C4H6N2+2H]2+"= list(mass_multi = 1 / 2,
                          mass_add = (2 * get.formula("H", charge = 1)@mass + 2 * get.formula("C2H3N", charge = 0)@mass) / 2,
                          formula_add = "C4H8N2",
                          formula_sub = NA_character_,
                          charge = 2),
  "[M+C6H9N3+2H]2+" = list(mass_multi = 1 / 2,
                           mass_add = (2 * get.formula("H", charge = 1)@mass + 3 * get.formula("C2H3N", charge = 0)@mass) / 2,
                           formula_add = "C6H11N3",
                           formula_sub = NA_character_,
                           charge = 2),
  
  # single charged -----------------------------------------------------------
  "[M+H]+"        = list(mass_multi = 1,
                         mass_add =  get.formula("H", charge = 1)@mass,
                         formula_add = "H",
                         formula_sub = NA_character_,
                         charge = 1),
  "[M+Li]+"       = list(mass_multi = 1,
                         mass_add =  get.formula("Li", charge = 1)@mass,
                         formula_add = "Li",
                         formula_sub = NA_character_,
                         charge = 1),
  "[M+2Li-H]+"    = list(mass_multi = 1,
                         mass_add =  2 * get.formula("Li", charge = 1)@mass -  get.formula("H", charge = 1)@mass,
                         formula_add = "Li2",
                         formula_sub = "H",
                         charge = 1),
  "[M+NH4]+"      = list(mass_multi = 1,
                         mass_add = get.formula("NH4", charge = 1)@mass,
                         formula_add = "NH4",
                         formula_sub = NA_character_,
                         charge = 1),
  "[M+H2O+H]+"   = list(mass_multi = 1,
                        mass_add = 18.01056 + get.formula("H", charge = 1)@mass,
                        formula_add = "H3O",
                        formula_sub = NA_character_,
                        charge = 1),
  "[M+Na]+"       = list(mass_multi = 1,
                         mass_add = get.formula("Na", charge = 1)@mass,
                         formula_add = "Na",
                         formula_sub = NA_character_,
                         charge = 1),
  "[M+CH4O+H]+"  = list(mass_multi = 1,
                        mass_add = get.formula("H", charge = 1)@mass + get.formula("CH4O", charge = 0)@mass,
                        formula_add = "CH5O",
                        formula_sub = NA_character_,
                        charge = 1),
  "[M+K]+"        = list(mass_multi = 1,
                         mass_add = get.formula("K", charge = 1)@mass,
                         formula_add = "K",
                         formula_sub = NA_character_,
                         charge = 1),
  "[M+C2H3N+H]+"  = list(mass_multi = 1,
                         mass_add = get.formula("H", charge = 1)@mass + get.formula("C2H3N", charge = 0)@mass,
                         formula_add = "C2H4N",
                         formula_sub = NA_character_,
                         charge = 1),
  "[M+2Na-H]+"    = list(masS_multi = 1,
                         mass_add = 2 * get.formula("Na", charge = 1)@mass - get.formula("H", charge = 1)@mass,
                         formula_add = "Na2",
                         formula_sub = "H",
                         charge = 1),
  "[M+C3H8O+H]+"  = list(mass_multi = 1,
                         mass_add = get.formula("H", charge = 1)@mass + get.formula("C3H8O", charge = 0)@mass,
                         formula_add = "C3H9O",
                         formula_sub = NA_character_,
                         charge = 1),
  "[M+C2H3N+Na]+"   = list(mass_multi = 1,
                           mass_add = get.formula("Na", charge = 1)@mass + get.formula("C2H3N", charge = 0)@mass,
                           formula_add = "C2H3NNa",
                           formula_sub = NA_character_,
                           charge = 1),
  "[M+2K-H]+"     = list(mass_multi = 1,
                         mass_add = 2 * get.formula("K", charge = 1)@mass - get.formula("H", charge = 1)@mass,
                         formula_add = "K2",
                         formula_sub = "H",
                         charge = 1),
  "[M+C2H6OS+H]+"   = list(mass_multi = 1,
                           masS_add = get.formula("H", charge = 1)@mass + get.formula("C2H6OS", charge = 0)@mass,
                           formula_add = "C2H7OS",
                           formula_sub = NA_character_,
                           charge = 1),
  "[M+C4H6N2+H]+"   = list(mass_multi = 1,
                           mass_add = get.formula("H", charge = 1)@mass + 2 * get.formula("C2H3N", charge = 0)@mass,
                           formula_add = "C4H7N2",
                           formula_sub = NA_character_,
                           charge = 1),
  
  # dimers -------------------------------------------------------------------
  "[2M+H]+"       = list(mass_multi = 2,
                         mass_add = get.formula("H", charge = 1)@mass,
                         formula_add = "H",
                         formula_sub = NA_character_,
                         charge = 1),
  "[2M+NH4]+"     = list(mass_multi = 2,
                         mass_add = get.formula("NH4", charge = 1)@mass,
                         formula_add = "NH4",
                         formula_sub = NA_character_,
                         charge = 1),
  "[2M+Na]+"      = list(mass_multi = 2,
                         mass_add = get.formula("Na", charge = 1)@mass,
                         formula_add = "Na",
                         formula_sub = NA_character_,
                         charge = 1),
  "[2M+K]+"       = list(mass_multi = 2,
                         mass_add = get.formula("K", charge = 1)@mass,
                         formula_add = "K",
                         formula_sub = NA_character_,
                         charge = 1),
  "[2M+C2H3N+H]+"   = list(mass_multi = 2,
                           mass_add = get.formula("H", charge = 1)@mass + get.formula("C2H3N", charge = 0)@mass,
                           formula_add = "C2H4N",
                           formula_sub = NA_character_,
                           charge = 1),
  "[2M+C2H3N+Na]+"  = list(mass_multi = 2,
                           mass_add = get.formula("Na", charge = 1)@mass + get.formula("C2H3N", charge = 0)@mass,
                           formula_add = "C2H3NNa",
                           formula_sub = NA_character_,
                           charge = 1),
  
  # trimers -------------------------------------------------------------------
  "[3M+H]+"       = list(mass_multi = 3,
                         mass_add = get.formula("H", charge = 1)@mass,
                         formula_add = "H",
                         formula_sub = NA_character_,
                         charge = 1)
)

# make df from list of list
adduct_df_pos <- data.frame(do.call(rbind, adduct_list_pos), stringsAsFactors = FALSE)
adduct_df_pos$adduct <- row.names(adduct_df_pos)
adduct_df_pos <- adduct_df_pos[,order(names(adduct_df_pos))]

adduct_df_pos$charge <- unlist(adduct_df_pos$charge)
adduct_df_pos$formula_add <- unlist(adduct_df_pos$formula_add)
adduct_df_pos$formula_sub <- unlist(adduct_df_pos$formula_sub)
adduct_df_pos$mass_add <- unlist(adduct_df_pos$mass_add)
adduct_df_pos$mass_multi <- unlist(adduct_df_pos$mass_multi)

# write positive file
write.table(adduct_df_pos, file = "adducts_pos.txt", sep = "\t", quote = FALSE, col.names = TRUE, row.names = FALSE)
